"""Property-based tests for HTTPS enforcement.

**Feature: platform-mcp-servers, Property 11: HTTPS Enforcement**
**Validates: Requirements 7.2**

For any API URL generated by the system, the URL scheme shall be "https".
"""

import os
import pytest
from hypothesis import given, strategies as st, settings, HealthCheck
from urllib.parse import urlparse

from credora.mcp_servers.meta_ads import MetaAdsMCPServer
from credora.mcp_servers.meta_ads_client import MetaAdsClient, META_API_BASE_URL
from credora.mcp_servers.oauth import (
    build_auth_url,
    PLATFORM_AUTH_URLS,
    PLATFORM_TOKEN_URLS,
)


# Strategy for generating valid access tokens
access_token_strategy = st.text(
    alphabet=st.sampled_from("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"),
    min_size=10,
    max_size=100,
)

# Strategy for generating valid API endpoints
endpoint_strategy = st.text(
    alphabet=st.sampled_from("abcdefghijklmnopqrstuvwxyz0123456789/_-"),
    min_size=1,
    max_size=50,
).filter(lambda x: not x.startswith("//") and x.strip() != "")

# Strategy for generating valid user IDs
user_id_strategy = st.text(
    alphabet=st.sampled_from("abcdefghijklmnopqrstuvwxyz0123456789_-"),
    min_size=1,
    max_size=50,
)

# Strategy for generating valid redirect URIs (must be HTTPS)
redirect_uri_strategy = st.builds(
    lambda domain, path: f"https://{domain}.example.com/{path}",
    domain=st.text(
        alphabet=st.sampled_from("abcdefghijklmnopqrstuvwxyz"),
        min_size=3,
        max_size=20,
    ),
    path=st.text(
        alphabet=st.sampled_from("abcdefghijklmnopqrstuvwxyz0123456789/"),
        min_size=0,
        max_size=30,
    ),
)

# Strategy for generating valid state parameters
state_strategy = st.text(
    alphabet=st.sampled_from("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-"),
    min_size=10,
    max_size=50,
)

# Strategy for generating valid shop names (for Shopify)
shop_strategy = st.text(
    alphabet=st.sampled_from("abcdefghijklmnopqrstuvwxyz0123456789-"),
    min_size=3,
    max_size=30,
).filter(lambda x: not x.startswith("-") and not x.endswith("-"))


# Test client ID for OAuth tests
TEST_CLIENT_ID = "test_client_id_12345"


class TestHTTPSEnforcement:
    """
    **Feature: platform-mcp-servers, Property 11: HTTPS Enforcement**
    **Validates: Requirements 7.2**
    
    For any API URL generated by the system, the URL scheme shall be "https".
    """

    @settings(max_examples=100)
    @given(access_token=access_token_strategy)
    def test_meta_ads_client_base_url_is_https(self, access_token):
        """Meta Ads client base URL should always use HTTPS."""
        client = MetaAdsClient(access_token=access_token)
        base_url = client.get_api_base_url()
        
        parsed = urlparse(base_url)
        assert parsed.scheme == "https", f"Expected HTTPS, got {parsed.scheme}"

    @settings(max_examples=100)
    @given(
        access_token=access_token_strategy,
        endpoint=endpoint_strategy,
    )
    def test_meta_ads_client_build_url_is_https(self, access_token, endpoint):
        """All URLs built by Meta Ads client should use HTTPS."""
        client = MetaAdsClient(access_token=access_token)
        url = client._build_url(endpoint)
        
        parsed = urlparse(url)
        assert parsed.scheme == "https", f"Expected HTTPS, got {parsed.scheme}"

    def test_meta_api_base_url_constant_is_https(self):
        """META_API_BASE_URL constant should use HTTPS."""
        parsed = urlparse(META_API_BASE_URL)
        assert parsed.scheme == "https", f"Expected HTTPS, got {parsed.scheme}"

    def test_meta_ads_server_api_base_url_is_https(self):
        """Meta Ads MCP Server API base URL should use HTTPS."""
        server = MetaAdsMCPServer()
        base_url = server.get_api_base_url()
        
        parsed = urlparse(base_url)
        assert parsed.scheme == "https", f"Expected HTTPS, got {parsed.scheme}"

    @settings(max_examples=100)
    @given(
        state=state_strategy,
        redirect_uri=redirect_uri_strategy,
    )
    def test_meta_oauth_url_is_https(self, state, redirect_uri):
        """Meta OAuth authorization URL should use HTTPS."""
        url = build_auth_url(
            platform="meta",
            state=state,
            redirect_uri=redirect_uri,
            client_id=TEST_CLIENT_ID,
        )
        
        parsed = urlparse(url)
        assert parsed.scheme == "https", f"Expected HTTPS, got {parsed.scheme}"

    @settings(max_examples=100)
    @given(
        state=state_strategy,
        redirect_uri=redirect_uri_strategy,
    )
    def test_google_oauth_url_is_https(self, state, redirect_uri):
        """Google OAuth authorization URL should use HTTPS."""
        url = build_auth_url(
            platform="google",
            state=state,
            redirect_uri=redirect_uri,
            client_id=TEST_CLIENT_ID,
        )
        
        parsed = urlparse(url)
        assert parsed.scheme == "https", f"Expected HTTPS, got {parsed.scheme}"

    @settings(max_examples=100)
    @given(
        state=state_strategy,
        redirect_uri=redirect_uri_strategy,
        shop=shop_strategy,
    )
    def test_shopify_oauth_url_is_https(self, state, redirect_uri, shop):
        """Shopify OAuth authorization URL should use HTTPS."""
        url = build_auth_url(
            platform="shopify",
            state=state,
            redirect_uri=redirect_uri,
            shop=shop,
            client_id=TEST_CLIENT_ID,
        )
        
        parsed = urlparse(url)
        assert parsed.scheme == "https", f"Expected HTTPS, got {parsed.scheme}"

    def test_all_platform_auth_urls_are_https(self):
        """All platform auth URLs should use HTTPS."""
        for platform, url in PLATFORM_AUTH_URLS.items():
            # Shopify URL has placeholder, check the template
            if "{shop}" in url:
                url = url.replace("{shop}", "testshop")
            
            parsed = urlparse(url)
            assert parsed.scheme == "https", f"Platform {platform} auth URL is not HTTPS: {url}"

    def test_all_platform_token_urls_are_https(self):
        """All platform token URLs should use HTTPS."""
        for platform, url in PLATFORM_TOKEN_URLS.items():
            # Shopify URL has placeholder, check the template
            if "{shop}" in url:
                url = url.replace("{shop}", "testshop")
            
            parsed = urlparse(url)
            assert parsed.scheme == "https", f"Platform {platform} token URL is not HTTPS: {url}"

    @settings(max_examples=100)
    @given(
        access_token=access_token_strategy,
        endpoint=endpoint_strategy,
    )
    def test_build_url_rejects_non_https_base(self, access_token, endpoint):
        """_build_url should reject attempts to use non-HTTPS URLs."""
        client = MetaAdsClient(access_token=access_token)
        
        # The client should always produce HTTPS URLs
        url = client._build_url(endpoint)
        assert url.startswith("https://"), f"URL should start with https://, got: {url}"

    @settings(max_examples=100)
    @given(
        platform=st.sampled_from(["meta", "google", "shopify"]),
        state=state_strategy,
        redirect_uri=redirect_uri_strategy,
    )
    def test_oauth_url_generation_always_https(self, platform, state, redirect_uri):
        """OAuth URL generation should always produce HTTPS URLs for all platforms."""
        # Shopify requires shop parameter
        shop = "testshop" if platform == "shopify" else None
        
        url = build_auth_url(
            platform=platform,
            state=state,
            redirect_uri=redirect_uri,
            shop=shop,
            client_id=TEST_CLIENT_ID,
        )
        
        parsed = urlparse(url)
        assert parsed.scheme == "https", f"Platform {platform} OAuth URL is not HTTPS: {url}"
